# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

container: mcr.microsoft.com/dotnet/core/sdk:2.1.700

variables:
  PublicRelease: "$[ eq(variables['Build.SourceBranch'], 'refs/heads/master') ]"
  PackageFolder: '$(Build.ArtifactStagingDirectory)/target'
  AnalyzersLogDirectory: '$(Agent.BuildDirectory)/_sdt/logs/CodeAnalysisLogs'

steps:
- script: |
    curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v6.2.0/powershell-6.2.0-linux-x64.tar.gz
    mkdir -p /tmp/microsoft/powershell/6.2.0
    tar zxf /tmp/powershell.tar.gz -C /tmp/microsoft/powershell/6.2.0
    chmod +x /tmp/microsoft/powershell/6.2.0/pwsh
    echo "##vso[task.setvariable variable=PATH]$PATH:/tmp/microsoft/powershell/6.2.0"
    echo "Powershell Core Installed"
  displayName: 'Install Powershell Core'
  condition: and(succeeded(), eq(variables['PublicRelease'], 'True'))

- task: DownloadSecureFile@1
  name: "AssemblyOriginatorKeyFile"
  displayName: 'Download Strong Name Public Key'
  inputs:
    secureFile: '$(SecureFileId)'
  condition: and(succeeded(), eq(variables['PublicRelease'], 'True'))

- task: DotNetCoreCLI@2
  displayName: 'DotNet Restore'
  inputs:
    command: restore
    projects: dirs.proj
    feedsToUse: config
    nugetConfigPath: NuGet.config

- task: DotNetCoreCLI@2
  displayName: 'DotNet Build'
  inputs:
    projects: dirs.proj
    arguments: '-p:CreateHardLinksForCopyLocalIfPossible=$(PublicRelease) -p:AssemblyOriginatorKeyFile=$(AssemblyOriginatorKeyFile.secureFilePath) --configuration Release --no-restore -warnaserror'

- task: PowerShell@2
  displayName: 'Process Build Outputs'
  inputs:
    targetType: filePath
    filePath: './.azure-pipelines/VsoAdapter.ps1'
    arguments: '-BuildOutputsEncoded "$(build.outputs)" -SourceDir "$(build.sourcesdirectory)"'
  condition: and(succeeded(), variables['build.outputs'], eq(variables['PublicRelease'], 'True'))

- task: DotNetCoreCLI@2
  displayName: 'DotNet Test'
  inputs:
    command: test
    projects: dirs.proj

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSigning dlls'
  inputs:
    ConnectedServiceName: '$(EsrpEndpointName)'
    FolderPath: '$(build.sourcesdirectory)'
    Pattern: '$(build.taskinput.sign)'
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
     [{
             "keyCode": "CP-233863-SN",
             "operationSetCode": "StrongNameSign",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-233863-SN",
             "operationSetCode": "StrongNameVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
     {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }
     ]
  condition: and(succeeded(), eq(variables['PublicRelease'], 'True'))

- task: PowerShell@2
  displayName: 'Fix Broken HardLinks'
  inputs:
    targetType: filePath
    filePath: './.azure-pipelines/VsoAdapter.ps1'
    arguments: '-HardlinksEncoded "$(build.taskinput.brokenhardlinks)" -SourceDir "$(build.sourcesdirectory)"'
  condition: and(succeeded(), variables['build.taskinput.brokenhardlinks'], eq(variables['PublicRelease'], 'True'))

- task: DotNetCoreCLI@2
  displayName: 'DotNet Pack'
  inputs:
    command: pack
    packagesToPack: dirs.proj
    packDirectory: '$(PackageFolder)'
    nobuild: true
    verbosityPack: Minimal
  condition: and(succeeded(), eq(variables['PublicRelease'], 'True'))

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSigning Packages'
  inputs:
    ConnectedServiceName: '$(EsrpEndpointName)'
    FolderPath: '$(PackageFolder)'
    Pattern: '*.nupkg'
    signConfigType: inlineSignParams
    inlineOperation: |
     [{
             "keyCode": "CP-401405",
             "operationSetCode": "NuGetSign",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-401405",
             "operationSetCode": "NuGetVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }]
  condition: and(succeeded(), eq(variables['PublicRelease'], 'True'))

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Packages'
  inputs:
    PathtoPublish: '$(PackageFolder)'
    ArtifactName: packages
  condition: and(succeeded(), eq(variables['PublicRelease'], 'True'))

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: CodeAnalysisLogs'
  inputs:
    PathtoPublish: '$(AnalyzersLogDirectory)'
    ArtifactName: CodeAnalysisLogs
  condition: and(succeeded(), eq(variables['PublicRelease'], 'True'))

- script: 'curl -X PATCH -u $(whoami):$SYSTEM_ACCESSTOKEN -H "Content-Type: application/json" -H "Accept: application/json;api-version=5.1" --data ''{"keepForever":true}'' "$(System.TeamFoundationCollectionUri)$(System.TeamProjectId)/_apis/build/builds/$(Build.BuildId)"'
  displayName: 'Keep Forever'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  condition: and(succeeded(), eq(variables['PublicRelease'], 'True'))